### ISSUE TITLE
[Bug] Alchemy and Void Walker Enchantment on everything

### ISSUE THREAD

**Issue by drakray** [CammiePone/Voidaic-Arcania#1]
Self explanatory, JEI tell me I can put your 2 Enchants on pretty much anything, dirt included.

**Comment by CammiePone** [comment]
Hm... that is weird. I think it's been fixed in this coming update, though. I've done what the game says to do to specify what can be enchanted, though, so hopefully it won't persist.

**Comment by ModMCdl** [comment]
I cannot replicate this bug in my dev environment any more, so I'm going to close this issue.
