### ISSUE TITLE
Crash when entering nether

### ISSUE THREAD

**Issue by Ayrion** [CammiePone/Voidaic-Arcania#4]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  No More Glowing Pots (nomoreglowingpots-1.0.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 11/12/18 11:26 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.camellias.voidaicarcania.world.gen.WorldGenCustomOres.runGenerator(WorldGenCustomOres.java:62)
	at com.camellias.voidaicarcania.world.gen.WorldGenCustomOres.generate(WorldGenCustomOres.java:37)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1247_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:739)
	at net.minecraft.world.World.func_72838_d(World.java:1208)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.camellias.voidaicarcania.world.gen.WorldGenCustomOres.runGenerator(WorldGenCustomOres.java:62)
	at com.camellias.voidaicarcania.world.gen.WorldGenCustomOres.generate(WorldGenCustomOres.java:37)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1247_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:739)
	at net.minecraft.world.World.func_72838_d(World.java:1208)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@30578d93
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 858289960 bytes (818 MB) / 3689938944 bytes (3519 MB) up to 5488246784 bytes (5234 MB)
	JVM Flags: 4 total; -Xmx5888m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 20, allocated: 1, tallocated: 21
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version            | Source                                         | Signature                                |
	|:--------- |:-------------------------------------------- |:------------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2             | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42               | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99          | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.5.2768       | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                    | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | aether_legacy                                | 1.12.2-v3.2        | aether_legacy-1.12.2-v3.2.jar                  | None                                     |
	| UCHIJAAAA | baubles                                      | 1.5.2              | Baubles-1.12-1.5.2.jar                         | None                                     |
	| UCHIJAAAA | astralsorcery                                | 1.10.3             | astralsorcery-1.12.2-1.10.3.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | quark                                        | r1.5-130           | Quark-r1.5-130.jar                             | None                                     |
	| UCHIJAAAA | autoreglib                                   | 1.3-20             | AutoRegLib-1.3-20.jar                          | None                                     |
	| UCHIJAAAA | betteranimals                                | 3.0                | betteranimals-3.0.jar                          | None                                     |
	| UCHIJAAAA | betteranimalsplus                            | 2.0.0              | betteranimalsplus-2.0.0.jar                    | None                                     |
	| UCHIJAAAA | bibliocraft                                  | 2.4.5              | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| UCHIJAAAA | jei                                          | 4.13.1.222         | jei_1.12.2-4.13.1.222.jar                      | None                                     |
	| UCHIJAAAA | forestry                                     | 5.8.2.372          | forestry_1.12.2-5.8.2.372.jar                  | None                                     |
	| UCHIJAAAA | binniecore                                   | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | binniedesign                                 | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | genetics                                     | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | botany                                       | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | extrabees                                    | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | extratrees                                   | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar               | None                                     |
	| UCHIJAAAA | biomesoplenty                                | 7.0.1.2402         | BiomesOPlenty-1.12.2-7.0.1.2402-universal.jar  | None                                     |
	| UCHIJAAAA | guideapi                                     | 1.12-2.1.7-62      | Guide-API-1.12-2.1.7-62.jar                    | None                                     |
	| UCHIJAAAA | bloodmagic                                   | 1.12.2-2.3.3-101   | BloodMagic-1.12.2-2.3.3-101.jar                | None                                     |
	| UCHIJAAAA | thaumcraft                                   | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| UCHIJAAAA | botania                                      | r1.10-357          | Botania r1.10-357.jar                          | None                                     |
	| UCHIJAAAA | chameleon                                    | 1.12-4.1.3         | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| UCHIJAAAA | ctm                                          | MC1.12.2-0.3.2.20  | CTM-MC1.12.2-0.3.2.20.jar                      | None                                     |
	| UCHIJAAAA | chisel                                       | MC1.12.2-0.2.1.35  | Chisel-MC1.12.2-0.2.1.35.jar                   | None                                     |
	| UCHIJAAAA | chiselsandbits                               | 14.28              | chiselsandbits-14.28.jar                       | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.2.2.353          | CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cucumber                                     | 1.1.1              | Cucumber-1.12.2-1.1.1.jar                      | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342         | movingworld-1.12-6.342-full.jar                | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@      | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| UCHIJAAAA | disenchanter                                 | 1.6                | disenchanter-[1.12]1.6.jar                     | None                                     |
	| UCHIJAAAA | ebwizardry                                   | 4.1.2              | Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar | None                                     |
	| UCHIJAAAA | elevatorid                                   | 1.3.6              | ElevatorMod-1.12.2-1.3.6.jar                   | None                                     |
	| UCHIJAAAA | enderstorage                                 | 2.4.5.135          | EnderStorage-1.12.2-2.4.5.135-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extraalchemy                                 | 0.3.8.6.1-release  | extraalchemy-0.3.8.6.1-release.jar             | None                                     |
	| UCHIJAAAA | rustic                                       | 1.0.12             | rustic-1.0.12.jar                              | None                                     |
	| UCHIJAAAA | growthcraft                                  | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_apples                           | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_bamboo                           | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_cellar                           | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_bees                             | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_fishtrap                         | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_grapes                           | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_hops                             | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_milk                             | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | growthcraft_rice                             | 4.0.4.100          | growthcraft-1.12.2-4.0.4.100.jar               | None                                     |
	| UCHIJAAAA | mantle                                       | 1.12-1.3.3.39      | Mantle-1.12-1.3.3.39.jar                       | None                                     |
	| UCHIJAAAA | inspirations                                 | 1.12.2-0.2.3       | Inspirations-1.12.2-0.2.3.jar                  | None                                     |
	| UCHIJAAAA | ironbackpacks                                | 1.12.2-3.0.8-12    | IronBackpacks-1.12.2-3.0.8-12.jar              | None                                     |
	| UCHIJAAAA | ironchest                                    | 1.12.2-7.0.52.837  | ironchest-1.12.2-7.0.52.837.jar                | None                                     |
	| UCHIJAAAA | jeibees                                      | 0.9.0.5            | jeibees-0.9.0.5-mc1.12.2.jar                   | None                                     |
	| UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2       | journeymap-1.12.2-5.5.2.jar                    | None                                     |
	| UCHIJAAAA | lunatriuscore                                | 1.2.0.42           | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| UCHIJAAAA | magicbees                                    | 1.0                | MagicBees-1.12.2-3.1.10.jar                    | None                                     |
	| UCHIJAAAA | morpheus                                     | 1.12-3.3.2         | Morpheus-1.12-3.3.2.jar                        | None                                     |
	| UCHIJAAAA | mysticalagriculture                          | 1.6.13             | MysticalAgriculture-1.12-1.6.13.jar            | None                                     |
	| UCHIJAAAA | harvestcraft                                 | 1.12.2z            | Pam's HarvestCraft 1.12.2za.jar                | None                                     |
	| UCHIJAAAA | primitivemobs                                | 1.1.6              | primitivemobs-1.1.6_beta.jar                   | None                                     |
	| UCHIJAAAA | twilightforest                               | 3.8.689            | twilightforest-1.12.2-3.8.689-universal.jar    | None                                     |
	| UCHIJAAAA | tconstruct                                   | 1.12.2-2.11.0.106  | TConstruct-1.12.2-2.11.0.106.jar               | None                                     |
	| UCHIJAAAA | xreliquary                                   | 1.12.2-1.3.4.780   | Reliquary-1.12.2-1.3.4.780.jar                 | None                                     |
	| UCHIJAAAA | ruins                                        | 17.1               | Ruins-1.12.2.jar                               | None                                     |
	| UCHIJAAAA | rusticthaumaturgy                            | 1.0                | Rustic Thaumaturgy-2.5a.jar                    | None                                     |
	| UCHIJAAAA | rusticbopwoods                               | 1.0                | rusticbopwoods-1.0.jar                         | None                                     |
	| UCHIJAAAA | schematica                                   | 1.8.0.169          | Schematica-1.12.2-1.8.0.169-universal.jar      | None                                     |
	| UCHIJAAAA | storagedrawers                               | 1.12-5.3.5         | StorageDrawers-1.12.2-5.3.7.jar                | None                                     |
	| UCHIJAAAA | tc6aspects4jei                               | 0.0.2a             | tc6aspects4jei-0.0.2a.jar                      | None                                     |
	| UCHIJAAAA | thaumictinkerer                              | 1.12.2-5.0-353c71c | thaumictinkerer-1.12.2-5.0-353c71c.jar         | None                                     |
	| UCHIJAAAA | tinkersaether                                | 1.2.0              | tinkersaether-1.2.0.jar                        | None                                     |
	| UCHIJAAAA | voidaicarcania                               | 0.4                | Voidaic Arcania v0.2.2b mc1.12.2.jar           | None                                     |
	| UCHIJAAAA | waystones                                    | 4.0.67             | Waystones_1.12.2-4.0.67.jar                    | None                                     |
	| UCHIJAAAA | immersiveengineering                         | 0.12-86            | ImmersiveEngineering-0.12-86.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
No More Glowing Pots (nomoreglowingpots-1.0.jar)
  zabi.minecraft.nomoreglowingpots.PotionTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Ace_1234'/70, l='New World', x=63.00, y=62.00, z=82.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ModMCdl** [comment]
Unable to recreate in our own environments.

Is this crash persistent? Or does it only happen every so often? Have you tried loading VA alone?

**Comment by Ayrion** [comment]
Persistent across at least three worlds, one of which only had VA and Baubles.
[VA Crashlog.txt](https://github.com/CammiePone/Voidaic-Arcania/files/2581138/VA.Crashlog.txt)

**Comment by ChiefLogan3010** [comment]
I also experience this crash, happened when I entered the nether from the void dimension, now whenever I load the world I get this crash:
https://gist.github.com/ChiefLogan3010/adbaf927a706cf14d54dfe87c85362fd
