### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Not-February** [CammiePone/Voidaic-Arcania#6]
https://gist.github.com/Febilian/e08d22ed35884e3ced6fbdef88020f37

Tested with nothing but Baubles and Voidaic Arcania installed.

**Comment by CammiePone** [comment]
Your problem is your Forge version. You need 1.12.2 - 14.23.5.2795

**Comment by Not-February** [comment]
Perhaps going forward then, I would suggest saying something in the changelogs whether the required Forge version to run the mod has changed. I've been running it before on the recommended version without issue(which is what I used in the test)

**Comment by CammiePone** [comment]
It shouldn't have crashed, and instead just said you had an outdated Forge version while loading, but I assume I did something wrong, since it crashed anyways.
