### ISSUE TITLE
Use Action gets stuck after entering the Void

### ISSUE THREAD

**Issue by ScytheIronclaw** [CammiePone/Voidaic-Arcania#7]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2837
Mod Version: 0.2.6b

After entering the void through the overworld, the Use Key action gets stuck, causing chests to open endlessly after closing them, and causing books to re-open after closing them.

After this glitch happens, if the player decides to change the controls from the options menu, it causes all keyboard input to no longer work in Minecraft until the game is completely closed and re-opened.

Steps to reproduce:
Enter the Void through the Overworld
Open the book given upon entering the dimension or open a chest.
Attempt to close the book or chest.
Become frustrated as the book or chest interface re-opens.
*I can only assume this issue will affect anything else that will open an interface.

**The crash report's crash reason will state that it was manually triggered via debug (F3+C) to generate a crashlog that hopefully captures what's going wrong here.

[crash-2019-05-10_03.13.29-client.txt](https://github.com/CammiePone/Voidaic-Arcania/files/3165290/crash-2019-05-10_03.13.29-client.txt)

**Comment by CammiePone** [comment]
This is a known bug, and has been fixed in the rewrite. But as the rewrite isn't anywhere near completion, it will be a while before it's released. I apologize for the inconvenience.

**Comment by ScytheIronclaw** [comment]
Sorry. I didn't know it was a known bug. I searched the past closed issues and didn't see this specific one listed.

**Comment by CammiePone** [comment]
Yeah, no one's mentioned it. Don't worry, you're fine. I discovered it on my own shortly after releasing the last file, and just took so long finding the fix, that the rewrite was already in progress.
